// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ElimarSoft.com.VSIX_Template
{
    internal sealed partial class Vsix
    {
        public const string Id = "ElimarSoft.com.VSIX_Template.6cb97e37-057f-48f8-b4c2-9b6df6eab6e8";
        public const string Name = "ElimarSoft.com.VSIX_Template";
        public const string Description = @"The easiest way to share links relevant to all developers in your team.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Juan Sala";
        public const string Tags = "";
    }
}
