// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ElimarSoft.com.VSIX_Template
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ElimarSoft_com_VSIX_TemplateString = "53ed6e50-ec5a-4cc1-870d-b2744946ef95";
        public static Guid ElimarSoft_com_VSIX_Template = new Guid(ElimarSoft_com_VSIX_TemplateString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int IDG_ES_ADDINS_GRP1 = 0x0100;
        public const int IDG_ES_ADDINS_GRP1_MENU1 = 0x0101;
        public const int IDG_ES_ADDINS_GRP1_MENU1_GRP1 = 0x0102;
        public const int IDG_ES_ADDINS_GRP1_MENU1_GRP1_BUTTTON1 = 0x0103;
        public const int IDG_ES_ADDINS_GRP1_MENU1_GRP1_BUTTTON2 = 0x0104;
        public const int IDBI_ES_CONTEXT_BUTTON1 = 0x0105;
        public const int IDBI_ES_CONTEXT_BUTTON2 = 0x0106;
        public const int IDBI_ES_CONTEXT_BUTTON3 = 0x0107;
        public const int IDBI_ES_CONTEXT_BUTTON4 = 0x0108;
        public const int IDBI_ES_CONTEXT_BUTTON5 = 0x0109;
        public const int IDM_ES_CONTEXT_MENU1 = 0x0110;
        public const int IDM_ES_CONTEXT_MENU1_GRP1 = 0x0111;
        public const int IDM_ES_CONTEXT_MENU1_GRP1_BUTTON1 = 0x0112;
        public const int IDM_ES_CONTEXT_MENU1_GRP1_BUTTON2 = 0x0113;
        public const int IDM_ES_CONTEXT_MENU2 = 0x0114;
        public const int IDM_ES_CONTEXT_MENU2_GRP1 = 0x0115;
        public const int IDM_ES_CONTEXT_MENU2_GRP1_BUTTON1 = 0x0116;
        public const int IDM_ES_CONTEXT_MENU2_GRP1_BUTTON2 = 0x0117;
        public const int IDG_ES_CONTEXT_PROJECT1 = 0x0118;
        public const int IDG_ES_CONTEXT_SOLUTION1 = 0x0119;
    }
}